apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-volume
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s/gitlab"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
